Enable an ecs-service to be load balanced, or connect to an external …
philips-software/terraform-aws-ecs-service pull request #18
Opened 2018-12-18 20:14 UTC by npalm

Added functionality to:
- Connect a target group to the ecs loadbalancer
- Let the module create a target group and listener rule to load balance the ecs service

2018-12-18 20:18 UTC, npalm commented
@mpas @gertjanmaas  pleas can you check the updates I suggest to the module. I focussed to keep the module backwards compatible. If we have breaking changes that we can explain in a few directions for migrations would be fine for me. 

Besides this I planning the following changes
- remove the dependency to aws_vpc_data vor the cidr, since this cause a change, even their isn't a change
- add Fargate as launch type

Since we have now a new module for the load balancer I think we should also drop in the future the load balancer complete from this module.

What do you think?

2018-12-19 07:43 UTC, gertjanmaas commented
Changes look good, just a couple of things that need some attention. The example needs to be fixed as it's asking for the value of the `dns_name` variable, which according to the `README.md` is disabled.

Both the planned changes are fine by me, Fargate support would be really nice to have.

I agree, once the load balanced ecs service module is tested we can deprecate that functionality from this module.

2018-12-19 08:26 UTC, gertjanmaas requested changes
Changes look good, just a couple of things that need some attention. The example needs to be fixed as it's asking for the value of the dns_name variable, which according to the README.md is disabled.

Both the planned changes are fine by me, Fargate support would be really nice to have.

I agree, once the load balanced ecs service module is tested we can deprecate that functionality from this module.

2018-12-19 08:26 UTC, gertjanmaas commented on main.tf
> +  target_group_arn = "${var.target_group_arn == "" ? element(concat(aws_alb_target_group.target_group.*.arn, list("")), 0) : var.target_group_arn}"
Why the concat of 2 lists and selecting an element? Can't this just be `aws_alb_target_group.target_group.arn`?

2018-12-19 08:26 UTC, gertjanmaas commented on variables.tf
> +  description = "In case `true` a load balanceer is created for the services which will be connected to the target group specified in `target_group_arn`. Creating a load balancer for an ecs service r
```suggestion
  description = "If `true` a load balancer is created for the service which will be connected to the target group specified in `target_group_arn`. Creating a load balancer for an ecs service requires a target group with a connected load balancer. To ensure the right order of creation, provide a list of depended arns in `ecs_services_dependencies`"
```

2018-12-19 08:26 UTC, gertjanmaas commented on variables.tf
> +  description = "Creates a services that can be load balanced, a ecs-services, target group and listener rule."
I don't understand the description, can you fix/rephrase it?

2018-12-19 08:26 UTC, gertjanmaas commented on variables.tf
> +  description = "Required for `enable_target_group_connection` provides the target group arn to be connected to the ecs load balancer. Ensure you provide the arn's of th listeners or listeners rule c
```suggestion
  description = "Required for `enable_target_group_connection` provides the target group arn to be connected to the ecs load balancer. Ensure you provide the arns of the listeners or listeners rule conntected to the target group as `ecs_services_dependencies`."
```

2018-12-19 08:26 UTC, gertjanmaas commented on variables.tf
> +  description = "The condtion fot he LB listener rule created when `enable_load_balanced` is set."
```suggestion
  description = "The condition for the LB listener rule which is created when `enable_load_balanced` is set."
```

2018-12-19 08:26 UTC, gertjanmaas commented on variables.tf
> +  description = "A list of arn can be provided to which the creation of the ecs services is depended."
```suggestion
  description = "A list of arns can be provided to which the creation of the ecs service is depended."
```

2018-12-19 08:26 UTC, gertjanmaas commented on README.md
> +| target_group_arn |  |
```suggestion

```

2018-12-19 08:29 UTC, npalm commented on main.tf
> +  target_group_arn = "${var.target_group_arn == "" ? element(concat(aws_alb_target_group.target_group.*.arn, list("")), 0) : var.target_group_arn}"
No the target group is optional and is controlled by a count, so we have to deal the case their is no target group defined in the module but injected.

2018-12-19 08:35 UTC, npalm commented on variables.tf
> +  description = "Creates a services that can be load balanced, a ecs-services, target group and listener rule."
Updates

2018-12-19 08:45 UTC, npalm commented on README.md
> +| target_group_arn |  |
Removed, duplicate

2018-12-19 08:45 UTC, npalm commented
@gertjanmaas Thanks for the feedback, comments are processed.

2018-12-19 09:30 UTC, gertjanmaas approved these changes

2018-12-19 09:31 UTC, merged