Support network load balancer
philips-software/terraform-aws-ecs-service pull request #6
Opened 2018-08-25 11:26 UTC by elviejokike

@npalm Let's check this one next week together.
Mainly, this change will allow to create use load balancers of type "network". By default, "application" will be used as it is currently doing.

2018-08-25 13:35 UTC, npalm reviewed
Looks great! 
- Please can you add an example for NLB
- What is the rationale for adding an NLB?

2018-08-25 13:38 UTC, npalm requested changes

2018-08-25 13:38 UTC, npalm commented on alb.tf
> +  // Only enable if ALB is required
Update comment, this in NLB or not?

2018-08-25 13:38 UTC, npalm commented on variables.tf
> +  description = "Load balancer type"
Please describe the options

2018-08-25 17:38 UTC, elviejokike commented
Network load balancers are useful, when using api gateways. If you want to connect AWS api gateway to resources in your VPC, network load balancer is the available alternative.

2018-08-27 12:38 UTC, npalm commented
@elviejokike Looks good!
- Is it possible to add an example in examples?
- Can you update the changelog?

2018-11-23 19:13 UTC, npalm commented
As discussed we should not create a VPC link for each service. We only need one per VPC. We can make the service load balancer enabled so the consumer of the module can connect the right load balancer and set up the VPC link. I will close the issue

2018-11-23 19:13 UTC, closed without merging